<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="cz.cvut.iarylser.service.UserServiceTest" tests="12" skipped="0" failures="0" errors="0" timestamp="2024-01-20T18:16:03" hostname="MACHINE" time="0.883">
  <properties/>
  <testcase name="convertToDTOList()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.809"/>
  <testcase name="authenticateUserFailure()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.02"/>
  <testcase name="deleteUserSucceeded()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.008"/>
  <testcase name="updateUserSucceeded()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.005"/>
  <testcase name="deleteUserFailure()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.011"/>
  <testcase name="getAllUsers()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.003"/>
  <testcase name="createUser_UserExists_ShouldThrowException()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.002"/>
  <testcase name="createUserSucceeded()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.004"/>
  <testcase name="convertToDTO()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.002"/>
  <testcase name="updateUserFailure()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.003"/>
  <testcase name="getUserById()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.001"/>
  <testcase name="authenticateUserSucceeds()" classname="cz.cvut.iarylser.service.UserServiceTest" time="0.002"/>
  <system-out><![CDATA[19:16:04.809 [Test worker] WARN cz.cvut.iarylser.service.UserService -- User with id 1 not found for deletion
19:16:04.833 [Test worker] WARN cz.cvut.iarylser.service.UserService -- User with id 1 not found for update
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
